name: frontend-knip

on:
  pull_request:
    paths:
      - 'frontend/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          # ãƒªãƒã‚¸ãƒˆãƒªã« .node-version ãŒã‚ã‚‹å ´åˆã¯ä»¥ä¸‹ã‚’åˆ©ç”¨ã—ã€
          # ãã“ã«æ›¸ã‹ã‚ŒãŸãƒãƒ¼ã‚¸ãƒ§ãƒ³ã‚’è‡ªå‹•çš„ã«ä½¿ç”¨
          node-version-file: '.node-version'
          # NPM ã‚­ãƒ£ãƒƒã‚·ãƒ¥ã‚’æœ‰åŠ¹ã«ã™ã‚‹
          cache: 'npm'

      # è¿½åŠ ã®ã‚­ãƒ£ãƒƒã‚·ãƒ¥ï¼ˆnode_modulesï¼‰ã‚’åˆ©ç”¨ã™ã‚‹å ´åˆã®ä¾‹
      - name: node modules cache
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: './node_modules'
          key: ${{ runner.os }}-build-${{ hashFiles('.node-version') }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        # ä¸Šã®ã‚­ãƒ£ãƒƒã‚·ãƒ¥ãŒãƒ’ãƒƒãƒˆã—ãªã‹ã£ãŸå ´åˆã«ã®ã¿ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«å®Ÿè¡Œ
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Knip
        id: knip-check
        # knip ã®å®Ÿè¡Œçµæœã‚’ /tmp/knip-report ã¸ãƒªãƒ€ã‚¤ãƒ¬ã‚¯ãƒˆ
        # continue-on-error: true ã¯ã€ŒKnip ã§æ¤œçŸ¥ãŒã‚ã£ã¦ã‚‚ã‚¸ãƒ§ãƒ–ã‚’ fail ã•ã›ãªã„ã€è¨­å®š
        run: npm run knip > /tmp/knip-report
        continue-on-error: true

      - name: Create PR comment
        uses: actions/github-script@v6
        if: steps.knip-check.outcome == 'failure'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs')
            const knipReport = fs.readFileSync('/tmp/knip-report', 'utf8')

            // ã‚³ãƒ¡ãƒ³ãƒˆæœ¬æ–‡
            const output = `
            ## ãƒ•ãƒ­ãƒ³ãƒˆã‚¨ãƒ³ãƒ‰ Knip ãƒ¬ãƒãƒ¼ãƒˆ

            Knip ã«ã‚ˆã‚Šæ¤œçŸ¥ã•ã‚ŒãŸæœªä½¿ç”¨ã‚³ãƒ¼ãƒ‰ã‚„ä¾å­˜é–¢ä¿‚ãŒã‚ã‚Šã¾ã™ã€‚ä¸è¦ã§ã‚ã‚Œã°å¯¾å¿œã‚’ã”æ¤œè¨ãã ã•ã„ã€‚
            \`npm run knip:fix\` ã¨ã„ã†ã‚³ãƒãƒ³ãƒ‰ã‚‚åˆ©ç”¨å¯èƒ½ã§ã™ã€‚
            
            <details>
              <summary>è©³ç´°ãƒ¬ãƒãƒ¼ãƒˆ ğŸ“–</summary>
              
              \`\`\`
              ${knipReport}
              \`\`\`
              
            </details>
            `

            // Pull Request ã«ã‚³ãƒ¡ãƒ³ãƒˆã‚’æŠ•ç¨¿
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
